language: cpp
compiler:
  - gcc
#  - clang # not supported yet

# Install a recent gcc, gcov and cmake,
# it will not be necessary once travis worker is based on ubuntu > 12.04.
# Install SWIG for bindings generation
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:kalakris/cmake # Non official cmake backport
  - sudo apt-get update -qq

install:
  - sudo apt-get install --yes swig cmake g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 100

# how to build
script:
  - cmake . && make -j && sudo make install
  - CTEST_OUTPUT_ON_FAILURE=1 make test
  - cd skeleton-subsystem
  - cmake . && make && sudo make install

notifications:
  email:
    - david.wagner@intel.com
  irc:
    - "chat.freenode.net#parameter-framework"

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Y+iKBg65e4dleuMwxAo1XSl/QkF4AtCe35ltu2DhPbeMJCywBmu0aeDb04oEaZJL+BxP+KMoRqRjeoGI3W/sh0gAq03iQ+P4C8KwRb9fdYPPVwH3NP3fyN27gFBH9GS8uMth68o2KP/oO/aqNwii/KbMZtubp7MhY/wnvz4DLCQ="

addons:
  coverity_scan:
    project:
      name: "dawagner/parameter-framework"
      description: "Plugin-based and rule-based framework for managing parameters"
    notification_email: david.wagner@intel.com
    build_command_prepend: "cmake ."
    build_command: "make -j 12"
    branch_pattern: coverity_scan
